spring:
  ######  sql数据源相关配置 ######
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #监控统计拦截的filters，conn, redis, stat, slf4j
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 50
      #获取连接等待超时时间
      max-wait: 60000
      #stat-view-servlet.allow: true
      ###### 解决8小时候断开连接的问题 start #######
      #指明在获取连接时进行检查
      test-on-borrow: true #设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      #指明是否在归还到池中前进行检验
      test-on-return: true
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      test-while-idle: true #设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      #间隔多久进行一次检测，检测需要关闭的空闲连接,以毫秒为单位.如果设置为非正数,则不运行空闲连接回收器线程
      time-between-eviction-runs-millis: 3600000
      ###### 解决8小时候断开连接的问题 end #######
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,
      #则查询必须是一个SQL SELECT并且必须返回至少一行记录
      validation-query: SELECT 'x'
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      monitor:
        urlSuffix: /druid/*    #监控的url地址后缀, 例如http://localhost:8080/druid/
        username: admin
        password: 123


##################### mybatis 相关配置 ###### start ##################
## mytatis配置
mybatis:
    ##定义pojo类
    type-aliases-package: com.iee.pagehelper.entity
    mapper-locations:
      - classpath:mapper/*.xml
      - classpath:com/wtx/mgt/mapper/*.xml
    configuration:
      database-id: mysql  # mysql, oracle

## github pagehelper配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
##################### mybatis 相关配置 ###### end ###################


server:
  port: 8800

logging:
  level:
    # 打印sql的log
    com.iee.pagehelper.mapper: debug
    org.springframework.web: debug
