server:
  port: 8080

file:
  location: D:\wms\template


###################### 文件上传配置 ###### start ############
local:
  folder: ${DiskLocation:/wms/}infile/
  exportfolder: ${DiskLocation:/wms/}exportfile/
  templatefolder: ${DiskLocation:/wms/}template/
  filesize: 20480
  fixType: xlsx,xls,txt,csv
  imgSize: 500
  imgType: jpg,png
  imgfolder: ${DiskLocation:/wms/}img/
####################### 文件上传配置 ###### end #############

###################### 功能插件配置 ###### start ############
swagger:
  #  open: true              #是否开启swagger,在生产环境下需要关闭
  protocol: http          #协议，http或https
  base-package: com.iee.filedownload.controller   #一定要写对，会在这个路径下扫描controller定义
  title: 文件下载(filedownload)REST API
  version: 1.0
  description: file download项目RESTful API

logging:
  level:
    root: info
    org.mongodb.driver: info
    com.netflix.discovery.DiscoveryClient: info
    com.iee: debug

###################### 功能插件配置 ###### end ############
